#!/bin/bash

# bash strict
IFS=$'\n\t'
set -euo pipefail

host=""
port=22
delay=0
proto="tcp"
sleep_time=1
connection_timeout=5
timeout=300
timeouted=0
wait_time=0
cmd=""
go=0
start_time=$(date +%s)
method=1
netcatcommands=(
 "netcat"
 "nc.openbsd"
 "nc.traditional"
 "nc"
)
netcatcmd="ERROR netcat command not found"

die(){
    local code=$1
    shift
    echo "$@"
    exit $code
}

usage(){
    cat <<'EOF'
NAME

    wait_for - wait_for a host to be reachable


SYNOPSIS

    wait_for ([--option=value] | host) [command]


DESCRIPTION

this command waits for a host:port to be reachable. It either executes a command directly or if no command is given it returns 0 or an error code.
the first non option argument is recognized as the beginning of the command. The command has to go last.
wait_for needs at least 1 argument. Either --host or a command.

OPTIONS

    --sleep=1          # Number of seconds to sleep between checks. (default:1)
    --delay=0          # Number of seconds to wait before starting to check the host. (default:0)
    --wait=0           # Number of seconds to wait after the host is reachable. (default:0)
    --timeout=300      # Number of seconds after which wait_for should abord with an timeout. (default:1)
    --icmp             # ping host instead of a tcp connection to port.
    --proto=icmp       # Proto ICMP or TCP.
    --port=22          # Port number to poll (Default:22/ssh) (unless icmp)
    --host=host        # A resolvable hostname or IP address.
    --help             # Shows this help page

COMMAND

if --host is not give then the first argument is used as host.
In any other case, every non option argument is considered as beginning of the command wait_for is supposed to execute.
if no command is given "wait_for" just returns an exit status code after finishing.


EXAMPLES

    wait_for myserver scp file root@myserver:/folder/  || echo "Timeout. myserver not reachable"
    wait_for --port=80 myserver && curl --HEAD http://myserver/ && notify-send --hint string:sound-name:dialog-ok "Server back up"
    wait_for --icmp --wait=300 my-super-secure-server && ssh my-super-secure-server systemctl restart start   # better not provoke fail2ban
    pon dsl; wait_for --icmp --wait=10 --host=dyndns.mydomain.com sudo /etc/firewall restart.

    if wait_for --wait=300 mad4milk.de ;
    then
        echo "do stuff"
    else
        case $? in
            22) echo "invalid argument. can't do stuff";;
            66) echo "timeout. can't do stuff";;
            *)  echo "$? something unexpectet happend";;
        esac
    fi


KNOWNBUGS

because I use a bash socket I can't control the timeout of the socket. I will add a netcat option in the future.
Under some circumstances the there are additional 30 seconds of sleep (the socket timeout) every poll.
This will reduce the poll rate and timeout will take longer. Up to 29 seconds.

--timeout is not percise because 'timeouts' of the check can introduce further delays.
    


EXIT STATUS

wait_for exits with ( from errno-base.h/errno.h taken from the linux kernel )

    0  - on success
    22 - invalid argument
    62 - time expired
    or the return code of COMMAND
    

ALTERNATIVES

If you're only looking for ssh/scp trying to connect until the ssh is reachable again you should take a
look into the ssh_config manpage."ConnectionAttempts" could be the option for you.


EOF
}

until [[ "$@" == '' ]]
do
    param="${1//=*/}"
    value="${1//*=/}"
    case $param in
        --help)
            usage
            exit 1
            ;;
        --host)
            [[ "$value" == '' ]] && die 22 "--host has to be an IP or hostname" # EINVAL /* Invalid argument */
            go=1
            host="$value"
            ;;
        --port)
            [[ "${value//[0-9a-zA-Z]/}" == '' ]] || die 22 "--port accepts a port number or a services name" # EINVAL /* Invalid argument */
            port="$value"
            go=1
            ;;
        --delay)
            [[ "${value//[0-9]/}" == '' ]] || die 22 "--delay only accepts seconds" # EINVAL /* Invalid argument */
            delay="$value"
            go=1
            ;;
        --sleep)
            [[ "${value//[0-9]/}" == '' ]] || die 22 "--sleep only accepts seconds" # EINVAL /* Invalid argument */
            sleep_time="$value"
            ;;
        --wait)
            [[ "${value//[0-9]/}" == '' ]] || die 22 "--sleep only accepts seconds" # EINVAL /* Invalid argument */
            wait_time="$value"
            ;;
        --timeout)
            [[ "${value//[0-9]/}" == '' ]] || die 22 "--timeout only accepts seconds" # EINVAL /* Invalid argument */
            timeout="$value"
            ;;
        --proto)
            [[ "${value}" != 'tcp' && "${value}" != "icmp" ]] && die 22 "--proto only accepts tcp or icmp as a parameter" # EINVAL /* Invalid argument */
            proto="$value"
            ;;
        --icmp)
            proto="icmp"
            ;;
        *)
            if [[ "$host" == "" ]];
            then
                go=1
                host=$1
                shift
                continue
            fi
            cmd="$@"
            go=1
            break
            ;;
    esac
    shift
done

real_timeout=$((delay+timeout))

check_timeout(){
    if [[ $(($(date +%s)-start_time)) -gt $real_timeout ]];
    then
        timeouted=1
        return 0
    fi
    return 1
}

for nc in ${netcatcommands[@]};
do
	if $nc -h 1>/dev/null 2>&1;
	then
       		method=2
		netcatcmd="$nc"
		break
	fi
done

if [[ $go -eq 1 ]];
then
    sleep "$delay"
    until check_timeout
    do
    if [[ "$proto" == "tcp" ]];
    then
        [[ $method -eq 1  ]] && (echo -n "" > "/dev/$proto/$host/$port") >/dev/null 2>&1 && break
	[[ $method -eq 2  ]] && $netcatcmd -d -z -w 1 "$host" "$port"  && break
    else
        ping -q -W2 -c1 "$host" >/dev/null  && break
        [[ $? > 1 ]] && die 101 "Network is unreachable" # ENETUNREACH  /* Network is unreachable */
    fi
        sleep $sleep_time
    done
    sleep "$wait_time"
    [[ $timeouted != 0 ]] && exit 62 # ETIME /* Timer expired */
    [[ "$cmd" == "" ]]    && exit  0 # success
    [[ "$cmd" != "" ]]    && eval "$@"
fi
exit $status
